hdfs:
        server: http://hdfs_hostname:50070
        hdfs_user: "test"
        hdfs_group: "foobarbaz"
        mount_root: "/users/test"
        kerberos: True
mount:
        dest_dir: /tmp/myhdfsmount

